# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('sequence', models.IntegerField()),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=65)),
                ('owner_name', models.CharField(max_length=65)),
                ('image', models.ImageField(blank=True, help_text='image size 230 x 150 (wxh)', upload_to='service_providers')),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('emaill', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('mobile', models.CharField(max_length=15)),
                ('mobile2', models.CharField(blank=True, max_length=15)),
                ('website', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maziad.Category')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
            },
        ),
    ]
